<?php
return array(
	'ctrl' => array(
		'title'	=> 'LLL:EXT:attoworld/Resources/Private/Language/locallang_db.xlf:tx_attoworld_domain_model_location',
		'label' => 'title',
		'tstamp' => 'tstamp',
		'crdate' => 'crdate',
		'cruser_id' => 'cruser_id',
		'dividers2tabs' => TRUE,
		'versioningWS' => 2,
		'versioning_followPages' => TRUE,

		'languageField' => 'sys_language_uid',
		'transOrigPointerField' => 'l10n_parent',
		'transOrigDiffSourceField' => 'l10n_diffsource',
		'delete' => 'deleted',
		'enablecolumns' => array(
			'disabled' => 'hidden',
			'starttime' => 'starttime',
			'endtime' => 'endtime',
		),
		'searchFields' => 'title,name,addfirstline,addsecondline,street,streetnumber,city,zipcode,country,',
		'iconfile' => \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extRelPath('attoworld') . 'Resources/Public/Icons/tx_attoworld_domain_model_location.gif'
	),
	'interface' => array(
		'showRecordFieldList' => 'sys_language_uid, l10n_parent, l10n_diffsource, hidden, title, addfirstline, name, addsecondline, street, streetnumber, city, zipcode, country',
	),
	'types' => array(
		'1' => array('showitem' => 'sys_language_uid;;;;1-1-1, l10n_parent, l10n_diffsource, hidden;;1, title, name, addfirstline, addsecondline, street, streetnumber, city, zipcode, country, --div--;LLL:EXT:cms/locallang_ttc.xlf:tabs.access, starttime, endtime'),
	),
	'palettes' => array(
		'1' => array('showitem' => ''),
	),
	'columns' => array(
	
                'location' => array(
                    'label' => 'Location',
                    'config' => array(
                        'type' => 'inline',
                        'foreign_table' => 'tx_attoworld_domain_model_personaddress',
                        'foreign_field' => 'tx_attoworld_domain_model_location',
                        'foreign_label' => 'tx_attoworld_domain_model_person',
                    ),
                ),
                'title' => array(
                    'label' => 'Title',
                    'config' => array(
                        'type' => 'input',
                        'size' => '255',
                    )
                ),
                'addfirstline' => array(
                    'label' => 'Additional Address First Line',
                    'config' => array(
                        'type' => 'input',
                        'size' => '255',
                    )
                ),
                'addsecondline' => array(
                    'label' => 'Additional Address Second Line',
                    'config' => array(
                        'type' => 'input',
                        'size' => '255',
                    )
                ),
                'name' => array(
                    'label' => 'Name',
                    'config' => array(
                        'type' => 'input',
                        'size' => '255',
                    )
                ),
                'city' => array(
                    'label' => 'City',
                    'config' => array(
                        'type' => 'select',
                        'renderType' => 'selectSingle',
                        'items' => array(
                            array('Garching'),
                            array('Munich'),
                            array('Jena'),
                            array('Berlin'),
                            array('Ditzingen'),
                            array('Kressbrunn'),
                            array('Vienna'),
                            array('Budapest'),
                            array('Paris'),
                            array('New York'),
                            array('Tokyo'),
                            array('London'),
                            array('Bristol'),
                            array('Milpitas'),
                            array('College Park'),
                            array('Amsterdam'),
                            array('Washington'),
                            array('Stevenage'),
                            array('Tulsa'),
                            array('São Paulo'),
                            array('Weinheim'),
                            array('Osaka'),
                            array('Los Alamitos'),
                            array('Mulhouse'),
                            array('Abingdon'),
                            array('Les Ulis'),
                            array('Palo Alto'),
                            array('Heidelberg'),
                            array('Hamburg'),
                            array('Karlsruhe'),
                            array('Lübeck'),
                            array('Rossendorf'),
                            array('Riyad'),
                            array('Berkeley'),
                            array('Heraklion'),
                            array('Athens'),
                            array('Düsseldorf'),
                            array('Dresden'),
                            array('Gräfelfing'),
                            array('Shanghai'),
                            array('Aachen'),
                            array('Belfast'),
                            array('Swindon'),
                            array('Oxford'),
                            array('Moscow'),
                            array('Milan'),
                            array('Los Angeles'),
                            array('Mainz'),
                            array('Novosibirsk'),
                            array('Hünstetten'),
                            array('Lund'),
                            array('Villigen'),
                            array('Atlanta'),
                            array('Okazaki'),
                            array('Hanover'),
                            array('Alzenau'),
                            array('Changchun'),
                            array('Perchtoldsdorf'),
                        ),
                    ),
                ),
                'zipcode' => array(
                    'label' => 'Zipcode',
                    'config' => array(
                        'type' => 'input',
                        'size' => '255',
                    )
                ),
                'street' => array(
                    'label' => 'Street',
                    'config' => array(
                        'type' => 'input',
                        'size' => '255',
                    )
                ),
                'streetnumber' => array(
                    'label' => 'Streetnumber',
                    'config' => array(
                        'type' => 'input',
                        'size' => '255',
                    )
                ),
                'country' => array(
                    'label' => 'Country',
                    'config' => array(
                        'type' => 'select',
                        'renderType' => 'selectSingle',
                        'items' => array(
                            array('holy see (vatican city state)', 'VA'),
                            array('cocos (keeling) islands', 'CC'),
                            array('guatemala', 'GT'),
                            array('japan', 'JP'),
                            array('sweden', 'SE'),
                            array('tanzania, united republic of', 'TZ'),
                            array('congo, the democratic republic of the', 'CD'),
                            array('guam', 'GU'),
                            array('myanmar', 'MM'),
                            array('algeria', 'DZ'),
                            array('mongolia', 'MN'),
                            array('pakistan', 'PK'),
                            array('singapore', 'SG'),
                            array('saint vincent and the grenadines', 'VC'),
                            array('central african republic', 'CF'),
                            array('guinea-bissau', 'GW'),
                            array('macao', 'MO'),
                            array('poland', 'PL'),
                            array('saint helena', 'SH'),
                            array('venezuela', 'VE'),
                            array('congo', 'CG'),
                            array('northern mariana islands', 'MP'),
                            array('saint pierre and miquelon', 'PM'),
                            array('slovenia', 'SI'),
                            array('zimbabwe', 'ZW'),
                            array('switzerland', 'CH'),
                            array('guyana', 'GY'),
                            array('martinique', 'MQ'),
                            array('pitcairn', 'PN'),
                            array('svalbard and jan mayen', 'SJ'),
                            array('virgin islands, british', 'VG'),
                            array('côte d\'ivoire', 'CI'),
                            array('mauritania', 'MR'),
                            array('slovakia', 'SK'),
                            array('montserrat', 'MS'),
                            array('sierra leone', 'SL'),
                            array('yemen', 'YE'),
                            array('virgin islands, u.s.', 'VI'),
                            array('cook islands', 'CK'),
                            array('indonesia', 'ID'),
                            array('malta', 'MT'),
                            array('san marino', 'SM'),
                            array('chile', 'CL'),
                            array('ireland', 'IE'),
                            array('lao people\'s democratic republic', 'LA'),
                            array('mauritius', 'MU'),
                            array('senegal', 'SN'),
                            array('cameroon', 'CM'),
                            array('finland', 'FI'),
                            array('lebanon', 'LB'),
                            array('maldives', 'MV'),
                            array('puerto rico', 'PR'),
                            array('somalia', 'SO'),
                            array('china', 'CN'),
                            array('fiji', 'FJ'),
                            array('saint lucia', 'LC'),
                            array('malawi', 'MW'),
                            array('palestinian territory, occupied', 'PS'),
                            array('colombia', 'CO'),
                            array('falkland islands (malvinas)', 'FK'),
                            array('mexico', 'MX'),
                            array('portugal', 'PT'),
                            array('viet nam', 'VN'),
                            array('malaysia', 'MY'),
                            array('suriname', 'SR'),
                            array('micronesia, federated states of', 'FM'),
                            array('mozambique', 'MZ'),
                            array('costa rica', 'CR'),
                            array('palau', 'PW'),
                            array('faroe islands', 'FO'),
                            array('sao tome and principe', 'ST'),
                            array('israel', 'IL'),
                            array('liechtenstein', 'LI'),
                            array('paraguay', 'PY'),
                            array('bosnia and herzegovina', 'BA'),
                            array('cuba', 'CU'),
                            array('isle of man', 'IM'),
                            array('el salvador', 'SV'),
                            array('cape verde', 'CV'),
                            array('france', 'FR'),
                            array('india', 'IN'),
                            array('sri lanka', 'LK'),
                            array('vanuatu', 'VU'),
                            array('barbados', 'BB'),
                            array('british indian ocean territory', 'IO'),
                            array('ukraine', 'UA'),
                            array('christmas island', 'CX'),
                            array('reunion', 'RE'),
                            array('syrian arab republic', 'SY'),
                            array('cyprus', 'CY'),
                            array('iraq', 'IQ'),
                            array('swaziland', 'SZ'),
                            array('bangladesh', 'BD'),
                            array('czech republic', 'CZ'),
                            array('iran, islamic republic of', 'IR'),
                            array('mayotte', 'YT'),
                            array('belgium', 'BE'),
                            array('iceland', 'IS'),
                            array('burkina faso', 'BF'),
                            array('ecuador', 'EC'),
                            array('italy', 'IT'),
                            array('oman', 'OM'),
                            array('bulgaria', 'BG'),
                            array('bahrain', 'BH'),
                            array('uganda', 'UG'),
                            array('liberia', 'LR'),
                            array('burundi', 'BI'),
                            array('estonia', 'EE'),
                            array('lesotho', 'LS'),
                            array('benin', 'BJ'),
                            array('lithuania', 'LT'),
                            array('egypt', 'EG'),
                            array('western sahara', 'EH'),
                            array('saint barthélemy', 'BL'),
                            array('luxembourg', 'LU'),
                            array('romania', 'RO'),
                            array('bermuda', 'BM'),
                            array('latvia', 'LV'),
                            array('brunei darussalam', 'BN'),
                            array('united states minor outlying islands', 'UM'),
                            array('bolivia', 'BO'),
                            array('kenya', 'KE'),
                            array('namibia', 'NA'),
                            array('libyan arab jamahiriya', 'LY'),
                            array('brazil', 'BR'),
                            array('kyrgyzstan', 'KG'),
                            array('new caledonia', 'NC'),
                            array('serbia', 'RS'),
                            array('bahamas', 'BS'),
                            array('hong kong', 'HK'),
                            array('cambodia', 'KH'),
                            array('bhutan', 'BT'),
                            array('kiribati', 'KI'),
                            array('niger', 'NE'),
                            array('qatar', 'QA'),
                            array('russian federation', 'RU'),
                            array('united states', 'US'),
                            array('heard island and mcdonald islands', 'HM'),
                            array('norfolk island', 'NF'),
                            array('bouvet island', 'BV'),
                            array('eritrea', 'ER'),
                            array('honduras', 'HN'),
                            array('nigeria', 'NG'),
                            array('rwanda', 'RW'),
                            array('botswana', 'BW'),
                            array('spain', 'ES'),
                            array('ethiopia', 'ET'),
                            array('nicaragua', 'NI'),
                            array('andorra', 'AD'),
                            array('belarus', 'BY'),
                            array('comoros', 'KM'),
                            array('united arab emirates', 'AE'),
                            array('turks and caicos islands', 'TC'),
                            array('belize', 'BZ'),
                            array('croatia', 'HR'),
                            array('saint kitts and nevis', 'KN'),
                            array('afghanistan', 'AF'),
                            array('netherlands', 'NL'),
                            array('chad', 'TD'),
                            array('uruguay', 'UY'),
                            array('antigua and barbuda', 'AG'),
                            array('haiti', 'HT'),
                            array('korea, democratic people\'s republic of', 'KP'),
                            array('uzbekistan', 'UZ'),
                            array('gabon', 'GA'),
                            array('hungary', 'HU'),
                            array('french southern territories', 'TF'),
                            array('united kingdom', 'GB'),
                            array('anguilla', 'AI'),
                            array('germany', 'DE'),
                            array('korea, republic of', 'KR'),
                            array('togo', 'TG'),
                            array('norway', 'NO'),
                            array('thailand', 'TH'),
                            array('grenada', 'GD'),
                            array('nepal', 'NP'),
                            array('south africa', 'ZA'),
                            array('wallis and futuna', 'WF'),
                            array('albania', 'AL'),
                            array('georgia', 'GE'),
                            array('tajikistan', 'TJ'),
                            array('armenia', 'AM'),
                            array('french guiana', 'GF'),
                            array('nauru', 'NR'),
                            array('tokelau', 'TK'),
                            array('netherlands antilles', 'AN'),
                            array('djibouti', 'DJ'),
                            array('kuwait', 'KW'),
                            array('timor-leste', 'TL'),
                            array('turkmenistan', 'TM'),
                            array('angola', 'AO'),
                            array('denmark', 'DK'),
                            array('guernsey', 'GG'),
                            array('tunisia', 'TN'),
                            array('ghana', 'GH'),
                            array('jersey', 'JE'),
                            array('morocco', 'MA'),
                            array('cayman islands', 'KY'),
                            array('niue', 'NU'),
                            array('dominica', 'DM'),
                            array('gibraltar', 'GI'),
                            array('kazakhstan', 'KZ'),
                            array('tonga', 'TO'),
                            array('antarctica', 'AQ'),
                            array('monaco', 'MC'),
                            array('argentina', 'AR'),
                            array('moldova, republic of', 'MD'),
                            array('american samoa', 'AS'),
                            array('dominican republic', 'DO'),
                            array('turkey', 'TR'),
                            array('montenegro', 'ME'),
                            array('panama', 'PA'),
                            array('austria', 'AT'),
                            array('greenland', 'GL'),
                            array('saint martin', 'MF'),
                            array('new zealand', 'NZ'),
                            array('australia', 'AU'),
                            array('gambia', 'GM'),
                            array('madagascar', 'MG'),
                            array('guinea', 'GN'),
                            array('zambia', 'ZM'),
                            array('trinidad and tobago', 'TT'),
                            array('marshall islands', 'MH'),
                            array('aruba', 'AW'),
                            array('peru', 'PE'),
                            array('saudi arabia', 'SA'),
                            array('åland islands', 'AX'),
                            array('guadeloupe', 'GP'),
                            array('tuvalu', 'TV'),
                            array('french polynesia', 'PF'),
                            array('solomon islands', 'SB'),
                            array('samoa', 'WS'),
                            array('canada', 'CA'),
                            array('equatorial guinea', 'GQ'),
                            array('jamaica', 'JM'),
                            array('seychelles', 'SC'),
                            array('taiwan, province of china', 'TW'),
                            array('azerbaijan', 'AZ'),
                            array('greece', 'GR'),
                            array('macedonia, the former yugoslav republic of', 'MK'),
                            array('papua new guinea', 'PG'),
                            array('sudan', 'SD'),
                            array('south georgia and the south sandwich islands', 'GS'),
                            array('jordan', 'JO'),
                            array('mali', 'ML'),
                            array('philippines', 'PH'),
                        ),
                        'size' => 1,
                        'maxitems' => 1,
                    ),
                ),
            
		'sys_language_uid' => array(
			'exclude' => 1,
			'label' => 'LLL:EXT:lang/locallang_general.xlf:LGL.language',
			'config' => array(
				'type' => 'select',
				'renderType' => 'selectSingle',
				'foreign_table' => 'sys_language',
				'foreign_table_where' => 'ORDER BY sys_language.title',
				'items' => array(
					array('LLL:EXT:lang/locallang_general.xlf:LGL.allLanguages', -1),
					array('LLL:EXT:lang/locallang_general.xlf:LGL.default_value', 0)
				),
			),
		),
		'l10n_parent' => array(
			'displayCond' => 'FIELD:sys_language_uid:>:0',
			'exclude' => 1,
			'label' => 'LLL:EXT:lang/locallang_general.xlf:LGL.l18n_parent',
			'config' => array(
				'type' => 'select',
				'renderType' => 'selectSingle',
				'items' => array(
					array('', 0),
				),
				'foreign_table' => 'tx_attoworld_domain_model_location',
				'foreign_table_where' => 'AND tx_attoworld_domain_model_location.pid=###CURRENT_PID### AND tx_attoworld_domain_model_location.sys_language_uid IN (-1,0)',
			),
		),
		'l10n_diffsource' => array(
			'config' => array(
				'type' => 'passthrough',
			),
		),

		't3ver_label' => array(
			'label' => 'LLL:EXT:lang/locallang_general.xlf:LGL.versionLabel',
			'config' => array(
				'type' => 'input',
				'size' => 30,
				'max' => 255,
			)
		),
	
		'hidden' => array(
			'exclude' => 1,
			'label' => 'LLL:EXT:lang/locallang_general.xlf:LGL.hidden',
			'config' => array(
				'type' => 'check',
			),
		),
		'starttime' => array(
			'exclude' => 1,
			'l10n_mode' => 'mergeIfNotBlank',
			'label' => 'LLL:EXT:lang/locallang_general.xlf:LGL.starttime',
			'config' => array(
				'type' => 'input',
				'size' => 13,
				'max' => 20,
				'eval' => 'datetime',
				'checkbox' => 0,
				'default' => 0,
				'range' => array(
					'lower' => mktime(0, 0, 0, date('m'), date('d'), date('Y'))
				),
			),
		),
		'endtime' => array(
			'exclude' => 1,
			'l10n_mode' => 'mergeIfNotBlank',
			'label' => 'LLL:EXT:lang/locallang_general.xlf:LGL.endtime',
			'config' => array(
				'type' => 'input',
				'size' => 13,
				'max' => 20,
				'eval' => 'datetime',
				'checkbox' => 0,
				'default' => 0,
				'range' => array(
					'lower' => mktime(0, 0, 0, date('m'), date('d'), date('Y'))
				),
			),
		),

		
	),
);