<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "attoworld"
 *
 * Auto generated by Extension Builder 2017-01-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Attoworld',
	'description' => 'The Extension for attoworld',
	'category' => 'plugin',
	'author' => 'Mandy Singh',
	'author_email' => 'mandy.singh@mpq.mpg.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);